### ISSUE TITLE
Explanation of bug

### ISSUE THREAD

**Issue by steveno** [Jinjinov/External-Ballistics-Library#1]
In the README you point out two bugs you found in the code. Can you give more detail on the second one?

```
##2. bug in original code:

ptr[10n+5]=RadtoMOA(atan(ptr[10n+4])); // Windage in MOA

should be:

ptr[10n+5]=RadtoMOA(atan(ptr[10n+4]/(12*x))); // Windage in MOA
```

**Comment by Jinjinov** [comment]
- we are calculating windage in Minutes Of Angle
- the RadtoMOA function accepts radians and converts them to Minutes Of Angle
- we are calculating the radians using the atan (arcus tangens) function
- see atan at http://www.cplusplus.com/reference/cmath/atan/
- atan should be calculated from the y / x fraction (which is very obvious if you look at the atan2)
- see atan2 at http://www.cplusplus.com/reference/cmath/atan2/
- the original code calls atan only with the y part - that is ptr[10n+4]
- the fixed code calls atan correctly with y / x - that is ptr[10n+4]/(12*x)
- windage is in inches, but range x is in feet (12 inches) - that is why we multiply: 12*x
